
CREATE DATABASE IF NOT EXISTS alx_book_store;
USE alx_book_store;


CREATE TABLE IF NOT EXISTS AUTHORS (
    AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(100)
);



CREATE TABLE IF NOT EXISTS BOOKS (
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    AUTHOR_ID INT,
    PRICE DECIMAL(10,2),
    PUBLISHED_YEAR INT
);


CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(20)
);


CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    STATUS VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    ORDER_DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT,
    BOOK_ID INT,
    QUANTITY INT,
    TOTAL_PRICE DECIMAL(10,2)
);
